[package]
name = "file_to_text"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.20.0"
clap = { version = "4.0.32", features = ["derive"] }
